main: dev.aurelium.aureliummobs.AureliumMobs
name: AureliumMobs
author: _OfTeN_
version: 1.18
api-version: 1.16
depend:
  - AureliumSkills
softdepend:
  - PlaceholderAPI
  - WorldGuard
commands:
  aureliummobs:
    aliases: [amobs, am]
