main: dev.aurelium.auramobs.AuraMobs
name: AuraMobs
authors: [Archyx, _OfTeN_]
version: ${projectVersion}
api-version: 1.16
depend:
  - AuraSkills
softdepend:
  - PlaceholderAPI
  - WorldGuard
permissions:
  auramobs.reload:
    default: op